## This script is a regression test of the consistency of values produced by
## this R package, against values generated by the original volpak code. Note
## that the original volpak code is not without bugs and the values produced are
## not necessarily closer to being "correct".
##
## There is a known issue with volpak_vold, when treeht = 0.0. This function is
## not tested.
##



## User defined

Tol <- 5e-5




## Attach packages

library(volpak)
library(testthat)




## Load DST data

data(hags)
hags$TreeHt <- 0




## Calculate test values for each tree

treeid <- unique(hags$TreeSeq)
comparison <- vector("list", length(treeid))
names(comparison) <- as.character(treeid)

for(x in treeid){

  df <- hags[hags$TreeSeq == x, ]

  tree <- volpak_tree(df$HAG, df$DUB, df$TreeHt)

  tmp <- data.frame(
    TotalVol = volpak_total_vol(tree, TRUE),
    VTM = volpak_vtm(df$HAG, df$DUB, df$TreeHt),
    # TDVOL07 = volpak_vol_to_tdub(tree, 7, TRUE),
    # VOLD07 = volpak_vold(7, df$HAG, df$DUB, df$TreeHt),
    HAG15cm = volpak_get_hag(tree, 15),
    HTD15cm = volpak_htd(15, df$HAG, df$DUB, df$TreeHt)
  )

  tmp$VOLHAG <- volpak_vol_to_hag(tree, tmp$HAG15cm, TRUE)
  tmp$VOLH <- volpak_volh(tmp$HAG15cm, df$HAG, df$DUB, df$TreeHt)

  comparison[[as.character(x)]] <- tmp

}


comparison <- do.call("rbind", comparison)




## Calculate differences, between test values and original volpak

comparison$TotalVolDiff <- with(comparison, TotalVol - VTM)
# comparison$TDVOL07Diff <- with(comparison, TDVOL07 - VOLD07)
comparison$HAGDiff <- with(comparison, HAG15cm - HTD15cm)
comparison$VOLHAGDiff <- with(comparison, VOLHAG - VOLH)





## Tests

test_that("Consistency test: Total volume (above stump)", {

  expect_false(any(comparison$TotalVol < 0))

  expect_false(any(is.na(comparison$TotalVol)))

  expect_true(max(abs(comparison$TotalVolDiff), na.rm = TRUE) < Tol)

})




# test_that("Consistency test: Volume (above stump) to 7cm SED", {
#
#   expect_false(any(comparison$TDVOL07 < 0))
#
#   expect_false(any(is.na(comparison$TDVOL07)))
#
#   expect_true(max(abs(comparison$TDVOL07Diff), na.rm = TRUE) < Tol)
#
# })




test_that("Consistency test: Height (above ground) to 15cm SED", {

  expect_false(any(comparison$HAG15cm < 0))

  expect_false(any(is.na(comparison$HAG15cm)))

  expect_true(max(abs(comparison$HAGDiff), na.rm = TRUE) < Tol)

})




test_that("Consistency test: Volume (above stump) to height of 15cm SED point", {

  expect_false(any(comparison$VOLHAG < 0))

  expect_false(any(is.na(comparison$VOLHAG)))

  expect_true(max(abs(comparison$VOLHAGDiff), na.rm = TRUE) < Tol)

})



