# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_volpak_tree <- function(height, radius, total_height, stump_height) {
    .Call(`_volpak_r_volpak_tree`, height, radius, total_height, stump_height)
}

r_total_vol <- function(tree, abovestump) {
    .Call(`_volpak_r_total_vol`, tree, abovestump)
}

r_get_hag <- function(tree, search_radius) {
    .Call(`_volpak_r_get_hag`, tree, search_radius)
}

r_get_radius <- function(tree, search_height) {
    .Call(`_volpak_r_get_radius`, tree, search_height)
}

r_vol_to_tdub <- function(tree, tdub, abovestump) {
    .Call(`_volpak_r_vol_to_tdub`, tree, tdub, abovestump)
}

r_vol_to_hag <- function(tree, hag, abovestump) {
    .Call(`_volpak_r_vol_to_hag`, tree, hag, abovestump)
}

r_list_measures <- function(tree) {
    .Call(`_volpak_r_list_measures`, tree)
}

r_list_sections <- function(tree) {
    .Call(`_volpak_r_list_sections`, tree)
}

r_list_stump <- function(tree) {
    .Call(`_volpak_r_list_stump`, tree)
}

r_volpak_tree_height <- function(tree) {
    .Call(`_volpak_r_volpak_tree_height`, tree)
}

r_volpak_stump_radius <- function(tree) {
    .Call(`_volpak_r_volpak_stump_radius`, tree)
}

r_volpak_stump_vol <- function(tree) {
    .Call(`_volpak_r_volpak_stump_vol`, tree)
}

r_volpak_ground_radius <- function(tree) {
    .Call(`_volpak_r_volpak_ground_radius`, tree)
}

r_volpak_print <- function(tree) {
    invisible(.Call(`_volpak_r_volpak_print`, tree))
}

r_volpak_vol_above_top <- function(tree) {
    .Call(`_volpak_r_volpak_vol_above_top`, tree)
}

r_vpakinit <- function(height, diameter, total_height) {
    invisible(.Call(`_volpak_r_vpakinit`, height, diameter, total_height))
}

r_vtm <- function(height, diameter, total_height) {
    .Call(`_volpak_r_vtm`, height, diameter, total_height)
}

r_htd <- function(diams, height, diameter, total_height) {
    .Call(`_volpak_r_htd`, diams, height, diameter, total_height)
}

r_vold <- function(diams, height, diameter, total_height) {
    .Call(`_volpak_r_vold`, diams, height, diameter, total_height)
}

r_volh <- function(hags, height, diameter, total_height) {
    .Call(`_volpak_r_volh`, hags, height, diameter, total_height)
}

