# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

times <- function(x, y) {
    .Call('_volpak_times', PACKAGE = 'volpak', x, y)
}

r_volpak_tree <- function(height, radius, total_height, stump_height) {
    .Call('_volpak_r_volpak_tree', PACKAGE = 'volpak', height, radius, total_height, stump_height)
}

r_total_vol <- function(abovestump, tree) {
    .Call('_volpak_r_total_vol', PACKAGE = 'volpak', abovestump, tree)
}

r_get_hag <- function(search_radius, tree) {
    .Call('_volpak_r_get_hag', PACKAGE = 'volpak', search_radius, tree)
}

r_vol_to_tdub <- function(tdub, abovestump, tree) {
    .Call('_volpak_r_vol_to_tdub', PACKAGE = 'volpak', tdub, abovestump, tree)
}

r_vol_to_hag <- function(hag, abovestump, tree) {
    .Call('_volpak_r_vol_to_hag', PACKAGE = 'volpak', hag, abovestump, tree)
}

r_vtm <- function(height, diameter, total_height) {
    .Call('_volpak_r_vtm', PACKAGE = 'volpak', height, diameter, total_height)
}

