# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_formcall <- function(formmod_SEXP, formsubmod_SEXP, ts_SEXP, dbh_SEXP, dbhba_SEXP, pltfinyr_SEXP, maxpltfinyr_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_formcall', PACKAGE = 'GAMERoutines', formmod_SEXP, formsubmod_SEXP, ts_SEXP, dbh_SEXP, dbhba_SEXP, pltfinyr_SEXP, maxpltfinyr_SEXP, trace_SEXP)
}

r_moddbhinccall <- function(dbhincmod_SEXP, age_SEXP, si_SEXP, sba_SEXP, dbh_SEXP, dbhba_SEXP, east_SEXP, north_SEXP, sf_SEXP, mgaaveyearrain_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_moddbhinccall', PACKAGE = 'GAMERoutines', dbhincmod_SEXP, age_SEXP, si_SEXP, sba_SEXP, dbh_SEXP, dbhba_SEXP, east_SEXP, north_SEXP, sf_SEXP, mgaaveyearrain_SEXP, trace_SEXP)
}

r_modmortcall <- function(mortmod_SEXP, dbh_SEXP, dbhba_SEXP, balmod_SEXP, age_SEXP, si_SEXP, sba_SEXP, mgaaveyearrain_SEXP, sfno_SEXP, x75pcstkgone_SEXP, thinatfirst_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_modmortcall', PACKAGE = 'GAMERoutines', mortmod_SEXP, dbh_SEXP, dbhba_SEXP, balmod_SEXP, age_SEXP, si_SEXP, sba_SEXP, mgaaveyearrain_SEXP, sfno_SEXP, x75pcstkgone_SEXP, thinatfirst_SEXP, trace_SEXP)
}

r_need_balmod <- function(model) {
    .Call('_GAMERoutines_r_need_balmod', PACKAGE = 'GAMERoutines', model)
}

r_modprunefreqcall <- function(prunefreqmod_SEXP, dbh_SEXP, dbhba_SEXP, prunedstk_SEXP, totstk_SEXP, sopu_SEXP, sawlogprop_SEXP, sfno_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_modprunefreqcall', PACKAGE = 'GAMERoutines', prunefreqmod_SEXP, dbh_SEXP, dbhba_SEXP, prunedstk_SEXP, totstk_SEXP, sopu_SEXP, sawlogprop_SEXP, sfno_SEXP, trace_SEXP)
}

r_modsiphtphtcall <- function(phtmod_SEXP, age_SEXP, si_SEXP, north_SEXP, mgaaveyearrain_SEXP, sf_SEXP, laname_SEXP, pltfinyr_SEXP, is1R_SEXP, isclone_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_modsiphtphtcall', PACKAGE = 'GAMERoutines', phtmod_SEXP, age_SEXP, si_SEXP, north_SEXP, mgaaveyearrain_SEXP, sf_SEXP, laname_SEXP, pltfinyr_SEXP, is1R_SEXP, isclone_SEXP, trace_SEXP)
}

r_modsiphtsicall <- function(phtmod_SEXP, age_SEXP, pht_SEXP, north_SEXP, mgaaveyearrain_SEXP, sf_SEXP, laname_SEXP, pltfinyr_SEXP, is1R_SEXP, isclone_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_modsiphtsicall', PACKAGE = 'GAMERoutines', phtmod_SEXP, age_SEXP, pht_SEXP, north_SEXP, mgaaveyearrain_SEXP, sf_SEXP, laname_SEXP, pltfinyr_SEXP, is1R_SEXP, isclone_SEXP, trace_SEXP)
}

r_modsiphtsiminsi <- function(phtmod_SEXP) {
    .Call('_GAMERoutines_r_modsiphtsiminsi', PACKAGE = 'GAMERoutines', phtmod_SEXP)
}

r_modsiphtsimaxsi <- function(phtmod_SEXP) {
    .Call('_GAMERoutines_r_modsiphtsimaxsi', PACKAGE = 'GAMERoutines', phtmod_SEXP)
}

r_treehtcall <- function(treehtmod_SEXP, dbh_SEXP, pht_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_treehtcall', PACKAGE = 'GAMERoutines', treehtmod_SEXP, dbh_SEXP, pht_SEXP, trace_SEXP)
}

r_modvolinit <- function(volcode, volmeasday, volmeasmth, volmeasyear) {
    .Call('_GAMERoutines_r_modvolinit', PACKAGE = 'GAMERoutines', volcode, volmeasday, volmeasmth, volmeasyear)
}

r_modvoldbhpht <- function(tdub, dbh, pht, mganorth, buttdefect, topdefect) {
    .Call('_GAMERoutines_r_modvoldbhpht', PACKAGE = 'GAMERoutines', tdub, dbh, pht, mganorth, buttdefect, topdefect)
}

r_modvoldbhtht <- function(tdub, dbh, tht, pht, mganorth, buttdefect, topdefect) {
    .Call('_GAMERoutines_r_modvoldbhtht', PACKAGE = 'GAMERoutines', tdub, dbh, tht, pht, mganorth, buttdefect, topdefect)
}

r_modvoltvp <- function(dbh, pht) {
    .Call('_GAMERoutines_r_modvoltvp', PACKAGE = 'GAMERoutines', dbh, pht)
}

r_modvoltvt <- function(dbh, treeht) {
    .Call('_GAMERoutines_r_modvoltvt', PACKAGE = 'GAMERoutines', dbh, treeht)
}

r_modvoltht <- function(dbh, pht) {
    .Call('_GAMERoutines_r_modvoltht', PACKAGE = 'GAMERoutines', dbh, pht)
}

r_modvoltprdub <- function(ht, dbh, tht) {
    .Call('_GAMERoutines_r_modvoltprdub', PACKAGE = 'GAMERoutines', ht, dbh, tht)
}

r_modvoltprht <- function(dub, dbh, tht) {
    .Call('_GAMERoutines_r_modvoltprht', PACKAGE = 'GAMERoutines', dub, dbh, tht)
}

r_modvoltprvol <- function(htMin, htMax, dbh, tht) {
    .Call('_GAMERoutines_r_modvoltprvol', PACKAGE = 'GAMERoutines', htMin, htMax, dbh, tht)
}

r_modvolmvldub <- function(hag, tht, dbh) {
    .Call('_GAMERoutines_r_modvolmvldub', PACKAGE = 'GAMERoutines', hag, tht, dbh)
}

r_SOPUDictSweep <- function(sweepcode_SEXP) {
    .Call('_GAMERoutines_r_SOPUDictSweep', PACKAGE = 'GAMERoutines', sweepcode_SEXP)
}

r_SOPUDictBranch <- function(branchcode_SEXP) {
    .Call('_GAMERoutines_r_SOPUDictBranch', PACKAGE = 'GAMERoutines', branchcode_SEXP)
}

r_SOPUDictFeature <- function(featurecode_SEXP) {
    .Call('_GAMERoutines_r_SOPUDictFeature', PACKAGE = 'GAMERoutines', featurecode_SEXP)
}

r_sstcall <- function(sstmod_SEXP, age_SEXP, si_SEXP, stk_SEXP, rain_SEXP, north_SEXP, pcted_SEXP, hybf2_SEXP, donotadjust_SEXP, trace_SEXP) {
    .Call('_GAMERoutines_r_sstcall', PACKAGE = 'GAMERoutines', sstmod_SEXP, age_SEXP, si_SEXP, stk_SEXP, rain_SEXP, north_SEXP, pcted_SEXP, hybf2_SEXP, donotadjust_SEXP, trace_SEXP)
}

r_volpak_tree <- function(height, radius, total_height, stump_height) {
    .Call('_GAMERoutines_r_volpak_tree', PACKAGE = 'GAMERoutines', height, radius, total_height, stump_height)
}

r_volpak_section <- function(base, mid, top) {
    .Call('_GAMERoutines_r_volpak_section', PACKAGE = 'GAMERoutines', base, mid, top)
}

r_volpak_point <- function(hag, radius) {
    .Call('_GAMERoutines_r_volpak_point', PACKAGE = 'GAMERoutines', hag, radius)
}

r_vol_section <- function(log) {
    .Call('_GAMERoutines_r_vol_section', PACKAGE = 'GAMERoutines', log)
}

r_total_vol <- function(height, radius, total_height, stump_height) {
    .Call('_GAMERoutines_r_total_vol', PACKAGE = 'GAMERoutines', height, radius, total_height, stump_height)
}

r_vtm <- function(height, diameter, total_height) {
    .Call('_GAMERoutines_r_vtm', PACKAGE = 'GAMERoutines', height, diameter, total_height)
}

r_get_hag <- function(search_radius, height, radius, total_height, stump_height) {
    .Call('_GAMERoutines_r_get_hag', PACKAGE = 'GAMERoutines', search_radius, height, radius, total_height, stump_height)
}

r_vol_to_tdub <- function(tdub, height, radius, total_height, stump_height) {
    .Call('_GAMERoutines_r_vol_to_tdub', PACKAGE = 'GAMERoutines', tdub, height, radius, total_height, stump_height)
}

r_vol_to_hag <- function(hag, height, radius, total_height, stump_height) {
    .Call('_GAMERoutines_r_vol_to_hag', PACKAGE = 'GAMERoutines', hag, height, radius, total_height, stump_height)
}

r_treeht_est <- function(method, height, radius, total_height, stump_height) {
    .Call('_GAMERoutines_r_treeht_est', PACKAGE = 'GAMERoutines', method, height, radius, total_height, stump_height)
}

